import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 18, marginBottom: 6, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 11, color: "#666", marginBottom: 20 },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    marginTop: 16,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    paddingBottom: 4,
    marginBottom: 4,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  cellRank: { width: 30, fontFamily: "Helvetica-Bold" },
  cellText: { flex: 1, paddingRight: 8 },
  cellCluster: { width: 80, color: "#666" },
  cellScore: { width: 60, textAlign: "right", fontFamily: "Helvetica-Bold" },
  cellExtra: { width: 60, textAlign: "right", color: "#666" },
  meta: { fontSize: 9, color: "#999", marginTop: 4 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#999",
    textAlign: "center",
  },
});

interface SessionMeta {
  question: string;
  shortCode: string;
  createdAt: number;
  participantCount?: number;
}

interface DotRow {
  text: string;
  cluster: string;
  points: number;
}

interface StockRow {
  text: string;
  cluster: string;
  avgRank: number;
  timesRanked: number;
}

interface MatrixRow {
  text: string;
  cluster: string;
  avgX: number;
  avgY: number;
  count: number;
}

function DotVotingReport({
  meta,
  rows,
}: {
  meta: SessionMeta;
  rows: DotRow[];
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{meta.question}</Text>
        <Text style={styles.subtitle}>
          Session {meta.shortCode} -{" "}
          {new Date(meta.createdAt).toLocaleDateString()} - Dot Voting Results
        </Text>

        <View style={styles.tableHeader}>
          <Text style={styles.cellRank}>#</Text>
          <Text style={styles.cellText}>Response</Text>
          <Text style={styles.cellCluster}>Cluster</Text>
          <Text style={styles.cellScore}>Points</Text>
        </View>

        {rows.map((row, idx) => (
          <View key={idx} style={styles.tableRow}>
            <Text style={styles.cellRank}>{idx + 1}</Text>
            <Text style={styles.cellText}>{row.text}</Text>
            <Text style={styles.cellCluster}>{row.cluster}</Text>
            <Text style={styles.cellScore}>{row.points}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by DocBrown - {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

function StockRankReport({
  meta,
  rows,
}: {
  meta: SessionMeta;
  rows: StockRow[];
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{meta.question}</Text>
        <Text style={styles.subtitle}>
          Session {meta.shortCode} -{" "}
          {new Date(meta.createdAt).toLocaleDateString()} - Stock Rank Results
        </Text>

        <View style={styles.tableHeader}>
          <Text style={styles.cellRank}>#</Text>
          <Text style={styles.cellText}>Response</Text>
          <Text style={styles.cellCluster}>Cluster</Text>
          <Text style={styles.cellScore}>Avg Rank</Text>
          <Text style={styles.cellExtra}>Ranked</Text>
        </View>

        {rows.map((row, idx) => (
          <View key={idx} style={styles.tableRow}>
            <Text style={styles.cellRank}>{idx + 1}</Text>
            <Text style={styles.cellText}>{row.text}</Text>
            <Text style={styles.cellCluster}>{row.cluster}</Text>
            <Text style={styles.cellScore}>
              {Math.round(row.avgRank * 10) / 10}
            </Text>
            <Text style={styles.cellExtra}>{row.timesRanked}x</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by DocBrown - {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

function MatrixReport({
  meta,
  rows,
  xLabel,
  yLabel,
}: {
  meta: SessionMeta;
  rows: MatrixRow[];
  xLabel: string;
  yLabel: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{meta.question}</Text>
        <Text style={styles.subtitle}>
          Session {meta.shortCode} -{" "}
          {new Date(meta.createdAt).toLocaleDateString()} - 2x2 Matrix Results
        </Text>

        <View style={styles.tableHeader}>
          <Text style={styles.cellText}>Response</Text>
          <Text style={styles.cellCluster}>Cluster</Text>
          <Text style={styles.cellScore}>Avg {xLabel}</Text>
          <Text style={styles.cellExtra}>Avg {yLabel}</Text>
          <Text style={{ ...styles.cellExtra, width: 40 }}>N</Text>
        </View>

        {rows.map((row, idx) => (
          <View key={idx} style={styles.tableRow}>
            <Text style={styles.cellText}>{row.text}</Text>
            <Text style={styles.cellCluster}>{row.cluster}</Text>
            <Text style={styles.cellScore}>
              {Math.round(row.avgX * 10) / 10}
            </Text>
            <Text style={styles.cellExtra}>
              {Math.round(row.avgY * 10) / 10}
            </Text>
            <Text style={{ ...styles.cellExtra, width: 40 }}>{row.count}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by DocBrown - {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function downloadPdf(
  mode: "dot_voting" | "stock_rank" | "matrix_2x2",
  meta: SessionMeta,
  rows: DotRow[] | StockRow[] | MatrixRow[],
  config?: { xAxisLabel?: string; yAxisLabel?: string }
) {
  let doc: React.ReactElement;
  switch (mode) {
    case "dot_voting":
      doc = <DotVotingReport meta={meta} rows={rows as DotRow[]} />;
      break;
    case "stock_rank":
      doc = <StockRankReport meta={meta} rows={rows as StockRow[]} />;
      break;
    case "matrix_2x2":
      doc = (
        <MatrixReport
          meta={meta}
          rows={rows as MatrixRow[]}
          xLabel={config?.xAxisLabel ?? "X Axis"}
          yLabel={config?.yAxisLabel ?? "Y Axis"}
        />
      );
      break;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const blob = await pdf(doc as any).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `docbrown-${meta.shortCode}-results.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
